version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      python: 3.8
    commands:
      - cd src
      - npm install
      - chmod +x deploy.sh
  build:
    commands:
      - . ../environments/${ENVFILE}.sh
      - ./deploy.sh PIPELINE

